[package]
name = "pir-radiostation-analyser"
version = "0.1.0"
authors = ["akrimpenfort <akrimpenfort@uni-osnabrueck.de>",
            "wimueller <wimueller@uni-osnabrueck.de>",
          ]

[dependencies]
hyper = "0.10.2"
time = "0.1.36"
